CREATE TABLE IF NOT EXISTS Media (
  user_id INTEGER NOT NULL,
  media_id INTEGER PRIMARY KEY AUTOINCREMENT,
  image_url CHAR(1000) NOT NULL,
  name CHAR(30) NOT NULL,
  description TEXT NOT NULL,
  category TEXT not NULL,
  genre TEXT NOT NULL,
  year INTEGER NOT NULL,
  duration CHAR(30) NOT NULL,
  watched BOOLEAN NOT NULL
);
