CREATE TABLE IF NOT EXISTS Media (
  media_id INTEGER PRIMARY KEY AUTOINCREMENT,
  name CHAR(30) UNIQUE NOT NULL,
  description TEXT NOT NULL,
  category TEXT not NULL,
  genre TEXT NOT NULL,
  year INTEGER NOT NULL,
  duration CHAR(30) NOT NULL,
  rating DECIMAL(1,1)
);
